import { IntegrationConnection } from '../headless/opsBlueprintTypes';

export const INITIAL_INTEGRATION_CONNECTIONS: IntegrationConnection[] = [
  {
    id: 'int_rechat',
    organizationId: 'nest-realty',
    provider: 'Rechat',
    status: 'connected',
    description: 'Syncs agent directories, active listings, and client contacts.',
    priority: 'high',
    connectedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['fetch_agents', 'fetch_listings', 'create_marketing_task'],
    notes: 'Access token verified. Webhook triggers active.'
  },
  {
    id: 'int_google_drive',
    organizationId: 'nest-realty',
    provider: 'Google Drive',
    status: 'connected',
    description: 'Hosts shared SOP manuals, listing folders, and compliance documents.',
    priority: 'high',
    connectedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['upload_files', 'link_sop_folder'],
    notes: 'Google service account auth authenticated.'
  },
  {
    id: 'int_google_calendar',
    organizationId: 'nest-realty',
    provider: 'Google Calendar',
    status: 'connected',
    description: 'Manages conference room bookings, training sessions, and critical deadlines.',
    priority: 'medium',
    connectedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['create_event', 'check_room_availability'],
    notes: 'Resource calendars Wilmington-1 and Wilmington-2 mapped.'
  },
  {
    id: 'int_gmail',
    organizationId: 'nest-realty',
    provider: 'Gmail',
    status: 'connected',
    description: 'Shared inbox operations intake integration (ops@nestrealty.com).',
    priority: 'high',
    connectedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['poll_emails', 'send_email_confirmation'],
    notes: 'Shared credentials setup with secure IMAP OAuth.'
  },
  {
    id: 'int_basecamp',
    organizationId: 'nest-realty',
    provider: 'Basecamp',
    status: 'connected',
    description: 'Project planning, coordination checklists, and vendor workflows.',
    priority: 'medium',
    connectedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['sync_todos', 'post_messages', 'assign_cards'],
    notes: 'Basecamp V3 OAuth connected & live webhook triggers active.'
  },
  {
    id: 'int_quickbooks',
    organizationId: 'nest-realty',
    provider: 'QuickBooks',
    status: 'connected',
    description: 'Read-only financial audit logs, invoice ledger, and accounts payables status.',
    priority: 'high',
    connectedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['list_expenses', 'fetch_vendor_balance', 'sync_payouts'],
    notes: 'QuickBooks Online ledger connected & P&L sync healthy.'
  },
  {
    id: 'int_twilio',
    organizationId: 'nest-realty',
    provider: 'Twilio',
    status: 'connected',
    description: 'Automated SMS intake, critical escalation texts, and status alerts.',
    priority: 'medium',
    connectedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['send_sms', 'receive_sms_intake'],
    notes: 'Twilio A2P 10DLC connected & SMS alert dispatch active.'
  },
  {
    id: 'int_slack',
    organizationId: 'nest-realty',
    provider: 'Slack',
    status: 'connected',
    description: 'Connect Slack if your team uses it so approved channels can send requests into Nest Ops.',
    priority: 'medium',
    connectedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['ingest_channel_messages', 'post_alerts'],
    notes: 'Slack Bot workspace integration connected & channel webhooks active.'
  },
  {
    id: 'int_teams',
    organizationId: 'nest-realty',
    provider: 'Microsoft Teams',
    status: 'connected',
    description: 'Connect Teams if your team uses it so approved messages and channels can create Nest Ops requests.',
    priority: 'medium',
    connectedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['ingest_team_messages', 'post_teams_alerts'],
    notes: 'Microsoft Azure Graph API connected.'
  },
  {
    id: 'int_transactions',
    organizationId: 'nest-realty',
    provider: 'Dotloop/SkySlope/Brokermint',
    status: 'connected',
    description: 'Dotloop, SkySlope, Brokermint transaction and compliance platform sync.',
    priority: 'high',
    connectedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['fetch_transaction_files', 'sync_checklists', 'approve_loop_documents'],
    notes: 'Dotloop API connected & transaction document sync active.'
  },
  {
    id: 'int_marketing_systems',
    organizationId: 'nest-realty',
    provider: 'Marketing Systems',
    status: 'connected',
    description: 'Listing launch assets, social requests, flyers, photography, and campaign materials.',
    priority: 'medium',
    connectedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    lastSyncAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    syncHealth: 'healthy',
    supportedActions: ['fetch_marketing_briefs', 'publish_listings', 'generate_collateral'],
    notes: 'Canva & Marketing Desk API bridges connected.'
  }
];
